name: R CMD check with rmdcheck

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'
          Rscript -e 'remotes::install_cran("rmarkdown")'
          Rscript -e 'remotes::install_cran("knitr")'
          Rscript -e 'remotes::install_cran("rmdcheck")'

      - name: R CMD check
        uses: r-lib/actions/check-r-package@v2

      - name: Run rmdcheck
        run: |
          rmdcheck::rmdcheck(".")
